FROM node:lts-alpine as builder

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
# COPY package-lock.json /usr/src/app/package-lock.json
RUN yarn install --network-timeout 100000

COPY . /usr/src/app
COPY ./build /usr/src/app/build

FROM nginx:alpine

# work dir 에 build 폴더 생성 /app/build
RUN mkdir ./build

# host pc의 현재경로의 build 폴더를 workdir 의 build 폴더로 복사
ADD ./build ./build

# nginx 기본 설정 삭제 후 config 복사
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d

# 위에서 생성한 앱의 빌드산출물을 nginx의 샘플 앱이 사용하던 폴더로 이동
# COPY --from=builder /usr/src/app/build /usr/share/nginx/html

# 80포트 오픈
EXPOSE 80

# container 실행
CMD ["nginx", "-g", "daemon off;"]
