FROM node:lts-alpine as builder

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
# COPY package-lock.json /usr/src/app/package-lock.json
RUN yarn && mv node_modules ../

COPY . /usr/src/app
COPY ./build /usr/src/app/build

FROM nginx:alpine

# nginx 기본 설정 삭제 후 config 복사
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d

# 위에서 생성한 앱의 빌드산출물을 nginx의 샘플 앱이 사용하던 폴더로 이동
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

# 80포트 오픈
EXPOSE 80

# container 실행
CMD ["nginx", "-g", "daemon off;"]
